import Head from "next/head";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import Product from "../components/Stock";

export default function Home() {
  return (
    <div >
      <Head>
        <title> Ney Florist Houndre</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section id="hero">
        <Hero />
      </section>
      <section id="product">
        <Product />
      </section>
      <section id="contact">
        <Footer />
      </section>
      
    </div>
  );
}
